version: '2'
services:
    springoauth2-app:
        image: springoauth2
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://springoauth2-mysql:3306/springoauth2?useUnicode=true&characterEncoding=utf8&useSSL=false
            - SECURITY_OAUTH2_RESOURCE_USER_INFO_URI=http://keycloak:9080/auth/realms/jhipster/protocol/openid-connect/userinfo
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
    springoauth2-mysql:
        extends:
            file: mysql.yml
            service: springoauth2-mysql
    keycloak:
        extends:
            file: keycloak.yml
            service: keycloak
